version: "3.9"
services:
  db:
    image: oscarh/hibernate:2.2.0 # H2 이미지
    container_name: h2db
    restart: always
    ports:
      - "8082:8082"  # H2 Console
    environment:
      H2_OPTIONS: '-tcpAllowOthers -tcpPort 9092' # H2 TCP 옵션
    volumes:
      - ./db/h2/data:/data
    entrypoint: ["java", "-jar", "/app/h2.jar", "-tcp", "-tcpAllowOthers", "-web", "-webAllowOthers", "-webPort", "8082"]

  app:
    image: your-spring-application-image
    ports:
      - "8080:8080"
    depends_on:
      - db
